version: '3'
services:
  sql-server-1:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Willian!@Cavalo125Ra
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Willian!@Cavalo125Ra  # Senha SA personalizada
      MSSQL_PID: Developer
      MSSQL_USER: SA
      MSSQL_PASSWORD: Willian!@Cavalo125Ra   # Senha SA personalizada
      MSSQL_DB: testeDB  # Nome do banco de dados personalizado
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
  # node-app:
  #   build:
  #     context: ./WebRota/ClientApp/
  #     dockerfile: Dockerfile.node  # Caminho relativo ao docker-compose.yml
  #   ports:
  #     - "3000:3000"
  aspnet-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sql-server-1
